[package]
name = "rather"
version = "0.1.0"
authors = ["Georg Lauterbach <infrastructure@itbsd.com>"]
edition = "2018"

[dependencies]
pnet = "0.26.0"
libc = "0.2.80"
hex = "0.4.2"

[build-dependencies]
cc = "1.0.62"
